[project]
name = "manim"
version = "0.1.0"
description = "Generates manim animations based on inputs using Google ADK"
authors = [
        {name = "Aidan Andrews", email = "aidan@aaxiom.org"},
        ]

license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
google-adk = ">=0.4.0"
google-generativeai = ">=0.3.0"
manim = ">=0.17.3"
litellm = ">=0.1.0"
python-dotenv = ">=1.0.0"
pydantic-settings = "^2.8.1"
tabulate = "^0.9.0"
google-auth = "^2.36.0"
requests = "^2.32.3"
google-adk = ">=0.0.1"
google-cloud-aiplatform = {extras = ["adk", "agent-engines"], version = "^1.88.0"}

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-mock = "^3.14.0"
scikit-learn = "^1.6.1"
pytest-cov = "^6.0.0"
pytest-asyncio = "^0.25.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
